# mail.yml workflow file for Nikola to build the website from the source branch.
# Copy to .github/workflows/main.yml and commit to start build of website.
# Ensure Settings --> Actions --> General --> Workflow permissions
# Check: "Read and write permissions" and "Save" 

on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        set-safe-directory: '*'      
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      #with:
      #  dry_run: false
